language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --editable . # Install it self
  - pip install --upgrade pytest # Upgrade pytest to lastest
  - pip install coveralls # Install coverall
script:
  - pytest tests
  - pytest tests --cov=learn_coverage
notifications:
  slack:
    on_success: never
    on_failure: never
after_success:
  coveralls